linters:
  enable-all: true
  disable:
    - funlen
    - wsl
    - wrapcheck
    - goerr113
    - exhaustivestruct
    - nestif
    - noctx
    - paralleltest
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default
    min-complexity: 70
  gocognit:
    # minimal code complexity to report, 30 by default
    min-complexity: 120
issues:
  exclude-rules:
    - text: "TLS InsecureSkipVerify set true"
      linters:
        - gosec
